[server]
host = "0.0.0.0"
port = 8080
service_token = "token" 
webhook_url = "http://0.0.0.0:8090/api/calc"


[minio]
host = "localhost"
port = 9000

[jwt]
expire_at_minutes = 10

[redis]
host = "localhost"
port = 6379
dial_timeout_sec=10
read_timeout_sec=10
app_prefix="api:"