[server]
host = "0.0.0.0"
port = 8080

[minio]
host = "localhost"
port = 9000
access_key = "admin"
secret_key = "admin1234"
bucket = "failivercheck"

[jwt]
secret_key = "secret_key"
expire_at_minutes = 10